---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld
  namespace: hello-openshift-arc
spec:
  selector:
    matchLabels:
      app: aks-helloworld
  replicas: 3
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
      containers:
        - name: aks-helloworld
          image: >-
            mcr.microsoft.com/azuredocs/aks-helloworld:v1
          ports:
            - containerPort: 80
