---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: arc-k8s-demo
   labels:
   name: demoapp
spec:
  type: NodePort
  selector:
    app: demoapp
  ports:
    - protocol: TCP
      port: 80
      nodePort: 8443
